-- DISCLAIMER: This script has been generated using ChatGPT and, although it
-- has been manually reviewed and tweaked to adjust the output, it still  may contain errors.

-- export_vga_palette.lua
-- Exports the current sprite's palette as a C array (RGB, VGA 6-bit values).
-- Prompts the user for filename, path, and whether to output in hex.

local spr = app.activeSprite
if not spr then
  app.alert("No active sprite!")
  return
end

local pal = spr.palettes[1]

-- Ask the user for export settings
local dlg = Dialog("Export Palette to C File")
dlg:file{ id="path", label="Save as", save=true, filetypes={"c", "h"} }
dlg:check{ id="hex", label="Use Hex Values", text="0x?? format", selected=false }
dlg:button{ id="ok", text="Export" }
dlg:button{ id="cancel", text="Cancel" }
dlg:show()

local data = dlg.data
if not data or not data.path or data.cancel then
  return
end

local filepath = data.path
local useHex = data.hex
local basename = filepath:match("([^/\\]+)%.%w+$") or "palette"

-- Build the C file content
local lines = {}

-- Create include guard
table.insert(lines, [[
/**
 * This file has been autogenerated using
 * `export-vga-palette` Aseprite script
 *
 * by OnePopCorn as part of PopCorn Bucket
 *
 * https://github.com/onepopcorn/popcorn-bucket
 */
]])

table.insert(lines, [[
#ifndef _PALETTE_H
#define _PALETTE_H
]])

-- Create Color type
table.insert(lines, [[
#ifndef Color
typedef struct {
    unsigned char r, g, b;
} Color;
#endif
]])

-- Generate colors array
local shortname = (spr.filename and spr.filename:match("([^/\\]+)$")) or "Untitled"
table.insert(lines, string.format("// Exported from %s", shortname))
table.insert(lines, string.format("// %d colors, VGA 6-bit per channel", #pal))
table.insert(lines, string.format("const Color %s[] = {", basename))

for i = 0, #pal - 1 do
  local c = pal:getColor(i)
  local r = math.floor(c.red   / 4)
  local g = math.floor(c.green / 4)
  local b = math.floor(c.blue  / 4)

  if useHex then
    table.insert(lines, string.format("    {0x%02X, 0x%02X, 0x%02X},", r, g, b))
  else
    table.insert(lines, string.format("    {%2d, %2d, %2d},", r, g, b))
  end
end

table.insert(lines, "};")
table.insert(lines, string.format("const int %s_color_count = %d;", basename, #pal))

-- Close include guard
table.insert(lines, "#endif // _PALETTE_H")

-- Write to file
local f = io.open(filepath, "w")
if not f then
  app.alert("Failed to write file:\n" .. filepath)
  return
end
f:write(table.concat(lines, "\n"))
f:close()

app.alert("Palette exported successfully:\n" .. filepath)
